version: '3.9'

services:
  api:
    build:
      context: ./
      dockerfile: ./api/docker/Dockerfile.dev
    command: /bin/bash -c "while sleep 1000; do :; done"
    working_dir: /home/dev
    networks:
      - api-network
    volumes:
      - ./:/home/dev:cached
    ports:
      - '3000:3000'

  db:
    image: postgres:latest
    expose:
      - "5433"
    ports:
      - "5433:5433"
    environment:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: password
    volumes:
      - ./api/db/db-data:/var/lib/mysql
      - ./api/db/postgres.cnf:/etc/postgres/postgres.cnf
    command: -p 5433
    networks:
      - api-network
    # app:
    # TODO    

    # proxy:
    #   image: nginx
    #   ports:
    #     - "80:80"
    #     - "443:443"
    #   restart: always
    #   volumes:
    #     - ./nginx/api-dev.nginx.conf:/etc/nginx/conf.d/api.nginx.conf
    #   networks:
    #     - api-network

networks:
  api-network:
    driver: bridge
    name: api-network
