version: '3.9'

services:
  api:
    build:
      context: ./
      dockerfile: ./api/docker/Dockerfile.stage
    command: /bin/bash -c "./wait-for-psql.sh db 5432 -- npm run prisma:migrate && npm run prisma:generate && npm run dev"
    working_dir: /home/dev
    networks:
      - api-network
    volumes:
      - ./:/home/dev:cached
      - ./wait-for-psql.sh:/usr/local/bin/wait-for-psql.sh
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    image: postgres:latest
    expose:
      - "5433"
    ports:
      - "5433:5433"
    environment:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: password
    volumes:
      - ./api/db/db-data:/var/lib/mysql
      - ./api/db/postgres.cnf:/etc/postgres/postgres.cnf
    command: -p 5433
    networks:
      - api-network

  proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/api-https-setup.nginx.conf:/etc/nginx/conf.d/api.nginx.conf
      - ./nginx/certbot/www:/var/www/certbot/:ro
      - ./nginx/certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - api-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certbot/www/:/var/www/certbot/:rw
      - ./nginx/certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
    name: api-network
