FROM node:18.16.0-alpine3.17

# Crée le répertoire de l'application
WORKDIR /api

# Copier package.json et package-lock.json
COPY ../src/package*.json ./

# Installer les dépendances
RUN apt-get install -y aws-cli && \
    npm install

# Copier le reste de l'application
COPY ../src/ .

# Expose le port 3000
EXPOSE 3000

# Commande pour démarrer l'application
CMD [ "npm", "start" ]
