# Utilise l'image Docker officielle de Nginx
FROM nginx

# Copie le fichier de configuration de Nginx dans le conteneur
COPY ./nginx/api-https-setup.nginx.conf /etc/nginx/conf.d/api.nginx.conf

# Expose les ports sur lesquels Nginx écoute
EXPOSE 80
EXPOSE 443

# Définit la commande par défaut à exécuter lorsque le conteneur est démarré
CMD ["nginx", "-g", "daemon off;"]
