FROM node:18.16.0-alpine3.17

WORKDIR /api

COPY ../package*.json ./

RUN npm install

RUN npm install -g typescript

RUN npm install prisma @prisma/client

COPY ../ .

# Compiler le code TypeScript
RUN tsc

EXPOSE 8080

CMD [ "npm", "start" ]

