# Utilise l'image Docker officielle de Postgres
FROM postgres:latest

# Copie le fichier de configuration de Postgres dans le conteneur
COPY ./api/db/postgres.cnf /etc/postgresql/postgresql.conf

# Expose le port sur lequel Postgres écoute
EXPOSE 5433

# Définit la commande par défaut à exécuter lorsque le conteneur est démarré
CMD ["postgres", "-p", "5433"]
